### PR TITLE
32960702566301 deprecate old photo upload endpoints

### PR DESCRIPTION
**Pull request by furcon**
https://app.asana.com/0/341927851945516/32960702566301
Deprecate /upload, /photos/upload endpoints.

### CODE REVIEW

**Comment by furcon** [comment]
@gavinsharp @mwstobo Please review.

**Comment by gavinsharp** [comment]
How about we just delete these? I don't think there's much value in leaving them there and marking them deprecated.

**Comment by creature** [comment]
I think we should give users at least a little heads-up that these endpoints are going away, and what they should use instead. 

If we wanted to be hardline about it, though, I'd add a warning along the lines of "Client keys registered after _date_ will not be able to access these endpoints", and then enforce that in the code.

**Comment by gavinsharp** [comment]
The endpoints aren't going away (at least not right away). I just want to remove their mention in the docs.

**Pull request merged**
